name: react-rust-postgres
services:
  frontend:
    build: 
      context: frontend
      dockerfile: ./Dockerfile
    networks:
      - web-facing
    ports:
      - 80:80

  backend:
    build:
      context: backend
      dockerfile: ./Dockerfile
    environment:
      - ADDRESS=0.0.0.0:8000
      - RUST_LOG=debug
      - PG_DBNAME=postgres
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=mysecretpassword
    networks:
      - web-facing
      - internal
    depends_on:
      - db
    ports:
      - 8000:8000

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - internal

networks:
  web-facing: {}
  internal: {}
