name: react-rust-postgres
services:
#  frontend:
#    oh-no: my-cat-bit-my-lochkarten-now-all-the-bits-are-flipped
  backend:
    build:
      context: backend
      dockerfile: ./Dockerfile
    environment:
      - RUST_LOG=debug
    networks:
      - web-facing
      - internal
    depends_on:
      - db
    ports:
      - 8000:8000

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - internal

networks:
  web-facing: {}
  internal: {}
